nelmio_api_doc:
    documentation:
        info:
            title: MyFlow
            version: 2.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            -   Bearer: [ ]
        paths:
            /api/v2/login:
                post:
                    summary: Authenticate and get JWT token.
                    requestBody:
                        description: Authenticate and get JWT token.
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        username:
                                            type: string
                                        password:
                                            type: string
                    responses:
                        '200':
                            description: Authenticated.
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                        '401':
                            description: Wrong credentials.
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            code:
                                                type: integer
                                            message:
                                                type: string
    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/api/v2(?!/documentation$) # Accepts routes under /api except /api/doc
